[run-boost-tests] Try twice to fetch sources
Signed-off-by: Dmitry Moskalchuk <dm@crystax.net>

diff --git a/tests/run-boost-tests b/tests/run-boost-tests
--- a/tests/run-boost-tests
+++ b/tests/run-boost-tests
@@ -1065,35 +1065,51 @@ fetch()
     run git submodule init || exit 1
     run git submodule sync --recursive || exit 1
     run git submodule update --recursive || exit 1
-    )
-    fail_panic "Cannot fetch $URL to $DIR"
+    ) || return 1
+
+    return 0
 }
 
 fetch_boost()
 {
     local DIR="$1"
 
-    dump "Fetching Boost sources"
-
-    fetch "$BOOST_GIT_URL" "$DIR" "$TAG"
+    local attempt
+    for attempt in 1 2; do
+        dump "Fetching Boost sources"
+        fetch "$BOOST_GIT_URL" "$DIR" "$TAG" && return 0
+        log "Cannot fetch $BOOST_GIT_URL to $DIR, trying again"
+        run rm -Rf $DIR
+    done
+    panic "Cannot fetch $BOOST_GIT_URL to $DIR"
 }
 
 fetch_boost_bb()
 {
     local DIR="$1"
 
-    dump "Fetching Boost build sources"
-
-    fetch "$BOOST_BUILD_GIT_URL" "$DIR" "develop"
+    local attempt
+    for attempt in 1 2; do
+        dump "Fetching Boost build sources"
+        fetch "$BOOST_BUILD_GIT_URL" "$DIR" "develop" && return 0
+        log "Cannot fetch $BOOST_BUILD_GIT_URL to $DIR, trying again"
+        run rm -Rf $DIR
+    done
+    panic "Cannot fetch $BOOST_BUILD_GIT_URL to $DIR"
 }
 
 fetch_boost_rr()
 {
     local DIR="$1"
 
-    dump "Fetching Boost regression sources"
-
-    fetch "$BOOST_REGRESSION_GIT_URL" "$DIR" "develop"
+    local attempt
+    for attempt in 1 2; do
+        dump "Fetching Boost regression sources"
+        fetch "$BOOST_REGRESSION_GIT_URL" "$DIR" "develop"
+        log "Cannot fetch $BOOST_REGRESSION_GIT_URL to $DIR, trying again"
+        run rm -Rf $DIR
+    done
+    panic "Cannot fetch $BOOST_REGRESSION_GIT_URL to $DIR"
 }
 
 BOOST_SRCDIR=$TEST_DIR/$TAG/src/boost
