[run-boost-tests] Fix adbrunner
Signed-off-by: Dmitry Moskalchuk <dm@crystax.net>

diff --git a/tests/run-boost-tests b/tests/run-boost-tests
--- a/tests/run-boost-tests
+++ b/tests/run-boost-tests
@@ -688,19 +688,24 @@ generate_adbrunner()
         echo '{'
         echo '    local CMD="$@"'
         echo '    local ADBCAP=$F.adbcap.$(uuidgen)'
+        echo '    local RC'
         echo '    log "RUN: $CMD"'
         echo '    rm -f $ADBCAP'
         echo '    $ADB shell "$CMD ; echo \"${RUNTAG}:\$?\"" 2>&1 \'
         echo '        | $STDBUF sed -e "s,[[:cntrl:]],,g" \'
         echo '        | $STDBUF tee $ADBCAP \'
         echo '        >>$LOG'
-        echo '    RC=$(sed -e "\$!d" $ADBCAP 2>/dev/null | sed "s,^.*${RUNTAG}:,,")'
-        echo '    log "EXIT CODE: $RC"'
-        echo '    if [ -z "$RC" ]; then'
-        echo '        log "ADB FAILED"'
+        echo '    sed -e "\$d" $ADBCAP'
+        echo '    local LAST=$(tail -n 1 $ADBCAP 2>/dev/null)'
+        echo '    echo "$LAST" | sed -e "s,${RUNTAG}:.*\$,,"'
+        echo '    echo "$LAST" | grep -q "$RUNTAG"'
+        echo '    if [ $? -eq 0 ]; then'
+        echo '        RC=$(echo "$LAST" | sed "s,^.*${RUNTAG}:,,")'
+        echo '        log "EXIT CODE: $RC"'
+        echo '    else'
+        echo '        log "ADB FAILED: $LAST"'
         echo '        RC=1'
         echo '    fi'
-        echo '    sed -e "s,${RUNTAG}:.*\$,," $ADBCAP'
         echo '    rm -f $ADBCAP'
         echo '    return $RC'
         echo '}'
