[run-boost-tests] Refactor logging
Signed-off-by: Dmitry Moskalchuk <dm@crystax.net>

diff --git a/tests/run-boost-tests b/tests/run-boost-tests
--- a/tests/run-boost-tests
+++ b/tests/run-boost-tests
@@ -133,10 +133,6 @@ fail_panic "Cannot create test directory: $TEST_DIR"
 
 setup_default_log_file $TEST_DIR/test.log
 
-TLOG=$TEST_DIR/tools.log
-( tail -F $TLOG | catlog ) &
-TPID=$!
-
 LOCKDIR="$TEST_DIR/lock"
 rm -Rf "$LOCKDIR"
 mkdir -p "$LOCKDIR"
@@ -147,6 +143,19 @@ fail_panic "Cannot create results directory: $RESULTS_PATH"
 
 STDBUF=
 which stdbuf >/dev/null 2>&1 && STDBUF="stdbuf -o0"
+
+mkcatlog()
+{
+    echo 'catlog ()'
+    echo '{'
+    if [ "$VERBOSE" = "yes" ] ; then
+        echo '    cat'
+    fi
+    if [ -n "$TMPLOG" ] ; then
+        echo '    cat >> '$TMPLOG
+    fi
+    echo '}'
+}
 
 mktool()
 {
@@ -227,10 +236,6 @@ adb_devices()
 
 cleanup()
 {
-    kill -INT $TPID 2>/dev/null
-    sleep 0.5
-    kill -KILL $TPID 2>/dev/null
-
     adb_devices | {
         while read D; do
             $ADB -s "$D" shell "rm -r $DEVICE_PATH 2>/dev/null"
@@ -396,9 +401,12 @@ generate_toolchain()
     local TOOL
     for TOOL in $CCS; do
         {
-            cat <<EOF
-#!/bin/sh
+            echo "#!/bin/sh"
+            echo ''
+            mkcatlog
+            echo ''
 
+            cat <<EOF
 if echo "\$@" | tr ' ' '\\n' | grep -q -x -e -c; then
     LINKER=no
 else
@@ -446,7 +454,7 @@ fi
 
 run()
 {
-    echo "## COMMAND: \$@" >>$TLOG
+    echo "## COMMAND: \$@" | catlog
     exec "\$@"
 }
 EOF
@@ -474,7 +482,10 @@ EOF
             echo "#!/bin/sh"
             echo 'run()'
             echo '{'
-            echo '    echo "## COMMAND: $@" >>'$TLOG
+            echo ''
+            mkcatlog
+            echo ''
+            echo '    echo "## COMMAND: $@" | catlog'
             echo '    exec "$@"'
             echo '}'
             case $TOOLCHAIN_TYPE in
@@ -497,7 +508,10 @@ EOF
             echo "#!/bin/sh"
             echo 'run()'
             echo '{'
-            echo '    echo "## COMMAND: $@" >>'$TLOG
+            echo ''
+            mkcatlog
+            echo ''
+            echo '    echo "## COMMAND: $@" | catlog'
             echo '    exec "$@"'
             echo '}'
             echo "run $GCCTCPATH/bin/$TCPREFIX-$TOOL \"\$@\""
@@ -555,10 +569,11 @@ generate_adbrunner()
     {
         echo '#!/bin/bash'
         echo ''
-        echo 'LOG='$TLOG
+        mkcatlog
+        echo ''
         echo 'MYCMD="$0 $@"'
         echo ''
-        echo 'echo "## COMMAND: $MYCMD" >>$LOG'
+        echo 'echo "## COMMAND: $MYCMD" | catlog'
         echo ''
         echo 'F=$1'
         echo 'shift'
@@ -587,10 +602,10 @@ generate_adbrunner()
         echo '{'
         echo '    local CMD="$@"'
         echo '    local ADBCAP=$F.adbcap.$(uuidgen)'
-        echo '    echo "## $PREFIX [$ANDROID_SERIAL] RUN: $CMD" >>$LOG'
+        echo '    echo "## $PREFIX [$ANDROID_SERIAL] RUN: $CMD" | catlog'
         echo '    rm -f $ADBCAP'
         echo '    $ADB shell "$CMD ; echo \$?" 2>&1 \'
-        echo '        | sed -e "s,[[:cntrl:]],,g" | $STDBUF tee $ADBCAP >>$LOG'
+        echo '        | sed -e "s,[[:cntrl:]],,g" | $STDBUF tee $ADBCAP | catlog'
         echo '    RC=$(sed -e "\$!d" $ADBCAP 2>/dev/null)'
         echo '    sed -e "\$d" $ADBCAP'
         echo '    rm -f $ADBCAP'
@@ -608,7 +623,7 @@ generate_adbrunner()
         echo '        adb_shell "mkdir -p $DST/$BSRC"'
         echo '        RC=$?'
         echo '        if [ $RC -ne 0 ]; then'
-        echo '            echo "## $PREFIX [$ANDROID_SERIAL] PUSH FAILED: $SRC" >>$LOG'
+        echo '            echo "## $PREFIX [$ANDROID_SERIAL] PUSH FAILED: $SRC" | catlog'
         echo '            $ADB shell "rm -r $DST" >/dev/null 2>&1'
         echo '            return $RC'
         echo '        fi'
@@ -616,11 +631,11 @@ generate_adbrunner()
         echo '    fi'
         echo ''
         echo '    local CMD="$ADB push $SRC $DST"'
-        echo '    echo "## $PREFIX [$ANDROID_SERIAL] PUSH: $CMD" >>$LOG'
-        echo '    $CMD >>$LOG 2>&1'
+        echo '    echo "## $PREFIX [$ANDROID_SERIAL] PUSH: $CMD" | catlog'
+        echo '    $CMD 2>&1 | catlog'
         echo '    RC=$?'
         echo '    if [ $RC -ne 0 ]; then'
-        echo '        echo "## $PREFIX [$ANDROID_SERIAL] PUSH FAILED: $SRC" >>$LOG'
+        echo '        echo "## $PREFIX [$ANDROID_SERIAL] PUSH FAILED: $SRC" | catlog'
         echo '        $ADB shell "rm -r $DST" >/dev/null 2>&1'
         echo '        return $RC'
         echo '    fi'
@@ -640,7 +655,7 @@ generate_adbrunner()
         echo ''
         echo '    $FLOCK 3'
         echo '    if [ $? -ne 0 ]; then'
-        echo '        echo "## $PREFIX [$ANDROID_SERIAL] LOCK FAILED" >>$LOG'
+        echo '        echo "## $PREFIX [$ANDROID_SERIAL] LOCK FAILED" | catlog'
         echo '    fi'
         echo ''
         echo '    $ADB shell "rm -r $DSTPATH" >/dev/null 2>&1'
@@ -651,7 +666,7 @@ generate_adbrunner()
         echo '        $STRIP --strip-unneeded $E >/dev/null 2>&1'
         echo '        adb_push "$E" "$DSTPATH/$BE" && adb_shell "chmod 0755 $DSTPATH/$BE"'
         echo '        if [ $? -ne 0 ]; then'
-        echo '            echo "## $PREFIX [$ANDROID_SERIAL] SKIP: $F" >>$LOG'
+        echo '            echo "## $PREFIX [$ANDROID_SERIAL] SKIP: $F" | catlog'
         echo '            exit 0'
         echo '        fi'
         echo '    done'
@@ -662,7 +677,7 @@ generate_adbrunner()
         echo '            BE=$(basename $E)'
         echo '            adb_push "$E" "$DSTPATH/$BE"'
         echo '            if [ $? -ne 0 ]; then'
-        echo '                echo "## $PREFIX [$ANDROID_SERIAL] SKIP: $F" >>$LOG'
+        echo '                echo "## $PREFIX [$ANDROID_SERIAL] SKIP: $F" | catlog'
         echo '                exit 0'
         echo '            fi'
         echo '            NEWARGS="$NEWARGS $DSTPATH/$BE"'
@@ -675,7 +690,7 @@ generate_adbrunner()
         echo '    RC=$?'
         echo '    $ADB shell "rm -r $DSTPATH" >/dev/null 2>&1'
         echo '    if [ $RC -ne 0 ]; then'
-        echo '        echo "## $PREFIX [$ANDROID_SERIAL] RUN FAILED [\$?=$RC]: $F" >>$LOG'
+        echo '        echo "## $PREFIX [$ANDROID_SERIAL] RUN FAILED [\$?=$RC]: $F" | catlog'
         echo '        exit $RC'
         echo '    fi'
         echo ''
