[run-boost-tests] Make adbrunner waiting for emulator if adb failed
Signed-off-by: Dmitry Moskalchuk <dm@crystax.net>

diff --git a/tests/run-boost-tests b/tests/run-boost-tests
--- a/tests/run-boost-tests
+++ b/tests/run-boost-tests
@@ -72,6 +72,9 @@ register_var_option "--libraries=<list>" LIBRARIES "Explicit list of libraries t
 DEVICE_PATH=/data/local/tmp/boost-$(uuidgen)
 register_var_option "--device-path=<path>" DEVICE_PATH "Path on device where to push files"
 
+ADBRUNNER_LOCK_DIRECTORY=$TEST_DIR/lock
+register_var_option "--adbrunner-lock-directory=<path>" ADBRUNNER_LOCK_DIRECTORY "Directory where to place per-emulator lock files for adbrunner"
+
 REPORTS_PATH=$TEST_DIR/reports
 register_var_option "--reports=<path>" REPORTS_PATH "Path to store HTML reports"
 
@@ -147,10 +150,6 @@ REGRESSION_DIR="$TEST_DIR/$TAG/regression"
 REPORT_DIR="$TEST_DIR/$TAG/report"
 
 setup_default_log_file $TEST_DIR/test.log
-
-LOCKDIR="$TEST_DIR/lock"
-mkdir -p "$LOCKDIR"
-fail_panic "Cannot create lock directory: $LOCKDIR"
 
 mkdir -p $REPORTS_PATH
 fail_panic "Cannot create results directory: $REPORTS_PATH"
@@ -639,12 +638,13 @@ generate_adbrunner()
         echo 'DEVPATH="'$DEVICE_PATH/$ABI'"'
         echo 'DSTPATH=$DEVPATH/$(uuidgen)'
         echo 'ADB="'$ADB'"'
-        echo 'LOCKDIR="'$LOCKDIR'"'
+        echo 'LOCKDIR="'$ADBRUNNER_LOCK_DIRECTORY'"'
         echo 'FLOCK="'$FLOCK'"'
         echo 'STRIP="'$STRIP'"'
         echo 'STDBUF="'$STDBUF'"'
         echo 'LIBDIR="'$LIBDIR'"'
         echo 'RUNTAG="'$RUNTAG'"'
+        echo 'ADBFAILED=/tmp/adbfailed.'$(uuidgen)
         echo ''
         echo 'LIBCRYSTAX="'$LIBCRYSTAX'"'
         echo 'GNULIBCXX="'$NDK_DIR'/sources/cxx-stl/gnu-libstdc++/4.9"'
@@ -691,6 +691,7 @@ generate_adbrunner()
         echo '    local RC'
         echo '    log "RUN: $CMD"'
         echo '    rm -f $ADBCAP'
+        echo '    rm -f $ADBFAILED'
         echo '    $ADB shell "$CMD ; echo \"${RUNTAG}:\$?\"" 2>&1 \'
         echo '        | $STDBUF sed -e "s,[[:cntrl:]],,g" \'
         echo '        | $STDBUF tee $ADBCAP \'
@@ -704,6 +705,7 @@ generate_adbrunner()
         echo '        log "EXIT CODE: $RC"'
         echo '    else'
         echo '        log "ADB FAILED: $LAST"'
+        echo '        touch $ADBFAILED >>$LOG 2>&1'
         echo '        RC=1'
         echo '    fi'
         echo '    rm -f $ADBCAP'
@@ -721,6 +723,7 @@ generate_adbrunner()
         echo '        adb_shell "mkdir -p $DST/$BSRC"'
         echo '        if [ $? -ne 0 ]; then'
         echo '            $ADB shell "rm -r $DST" >/dev/null 2>&1'
+        echo '            touch $ADBFAILED >>$LOG 2>&1'
         echo '            panic "PUSH FAILED: $SRC"'
         echo '        fi'
         echo '        DST=$DST/$BSRC'
@@ -731,94 +734,104 @@ generate_adbrunner()
         echo '    $CMD >>$LOG 2>&1'
         echo '    if [ $? -ne 0 ]; then'
         echo '        $ADB shell "rm -r $DST" >/dev/null 2>&1'
+        echo '        touch $ADBFAILED >>$LOG 2>&1'
         echo '        panic "PUSH FAILED: $SRC"'
         echo '    fi'
         echo '}'
         echo ''
-        echo '{'
+        echo 'while true; do'
+        echo '    {'
         if [ -n "$DEVICES_FROM" ]; then
-            echo '    cat '$DEVICES_FROM' 2>/dev/null'
+            echo '        cat '$DEVICES_FROM' 2>/dev/null'
         else
-            echo '    cat <<EOD'
+            echo '        cat <<EOD'
             adb_devices $ABI
             echo 'EOD'
         fi
-        echo '} | {'
-        echo 'while read D; do'
-        echo '    mkdir -p $LOCKDIR >/dev/null 2>&1'
-        echo '    ('
-        echo '    export ANDROID_SERIAL="$D"'
+        echo '    } | {'
+        echo '    while read D; do'
+        echo '        mkdir -p $LOCKDIR >/dev/null 2>&1'
+        echo '        ('
+        echo '        export ANDROID_SERIAL="$D"'
         echo ''
-        echo '    $FLOCK 3'
-        echo '    fail_panic "LOCK FAILED"'
+        echo '        exec 3>"$LOCKDIR/$D.lock"'
+        echo '        $FLOCK 3'
+        echo '        fail_panic "LOCK FAILED"'
         echo ''
-        echo '    log "START: $F $ARGS"'
+        echo '        log "START: $F $ARGS"'
         echo ''
-        echo '    adb_shell "mkdir -p $DEVPATH/lib && mkdir -p $DEVPATH/tmp && mkdir -p $DSTPATH"'
-        echo '    fail_panic "CANNOT CREATE REQUIRED DIRECTORIES"'
+        echo '        adb_shell "mkdir -p $DEVPATH/lib && mkdir -p $DEVPATH/tmp && mkdir -p $DSTPATH"'
+        echo '        fail_panic "CANNOT CREATE REQUIRED DIRECTORIES"'
         echo ''
-        echo '    for LIB in \'
-        echo '        $LIBCRYSTAX/libs/$ABI/libcrystax.so \'
-        echo '        $GNULIBCXX/libs/$ABI/libgnustl_shared.so \'
+        echo '        for LIB in \'
+        echo '            $LIBCRYSTAX/libs/$ABI/libcrystax.so \'
+        echo '            $GNULIBCXX/libs/$ABI/libgnustl_shared.so \'
         if [ -n "$ICU" ]; then
-            echo '        $ICU/libs/$ABI/lib*.so \'
+            echo '            $ICU/libs/$ABI/lib*.so \'
         fi
-        echo '        ; do'
+        echo '            ; do'
         echo ''
-        echo '        BLIB=$(basename $LIB)'
+        echo '            BLIB=$(basename $LIB)'
         echo ''
-        echo '        adb_shell "test -e $DEVPATH/lib/$BLIB"'
-        echo '        if [ $? -eq 0 ]; then'
-        echo '            continue'
-        echo '        fi'
+        echo '            adb_shell "test -e $DEVPATH/lib/$BLIB"'
+        echo '            if [ $? -eq 0 ]; then'
+        echo '                continue'
+        echo '            fi'
         echo ''
-        echo '        if [ ! -e $LIBDIR/$BLIB ]; then'
-        echo '            mkdir -p $LIBDIR'
-        echo '            fail_panic "MKDIR FAILED: $LIBDIR"'
-        echo '            cp -f $LIB $LIBDIR/'
-        echo '            fail_panic "COPY FAILED: $LIB -> $LIBDIR/"'
-        echo '            $STRIP --strip-unneeded $LIBDIR/$BLIB'
-        echo '            fail_panic "STRIP FAILED: $LIBDIR/$BLIB"'
-        echo '        fi'
+        echo '            if [ ! -e $LIBDIR/$BLIB ]; then'
+        echo '                mkdir -p $LIBDIR'
+        echo '                fail_panic "MKDIR FAILED: $LIBDIR"'
+        echo '                cp -f $LIB $LIBDIR/'
+        echo '                fail_panic "COPY FAILED: $LIB -> $LIBDIR/"'
+        echo '                $STRIP --strip-unneeded $LIBDIR/$BLIB'
+        echo '                fail_panic "STRIP FAILED: $LIBDIR/$BLIB"'
+        echo '            fi'
         echo ''
-        echo '        adb_push "$LIBDIR/$BLIB" "$DEVPATH/lib"'
-        echo '    done'
+        echo '            adb_push "$LIBDIR/$BLIB" "$DEVPATH/lib"'
+        echo '        done'
         echo ''
-        echo '    for E in $F $EXTRAS; do'
-        echo '        BE=$(basename $E)'
-        echo '        echo $BE | grep -q -x libcrystax.so && continue'
-        echo '        echo $BE | grep -q -x libgnustl_shared.so && continue'
-        if [ -n "$ICU" ]; then
-            echo '        echo $BE | grep -q "^libicu.*" && continue'
-        fi
-        echo '        $STRIP --strip-unneeded $E >/dev/null 2>&1'
-        echo '        adb_push "$E" "$DSTPATH/$BE" && adb_shell "chmod 0755 $DSTPATH/$BE"'
-        echo '    done'
-        echo ''
-        echo '    NEWARGS=""'
-        echo '    for E in $ARGS; do'
-        echo '        if [ -e $E ]; then'
+        echo '        for E in $F $EXTRAS; do'
         echo '            BE=$(basename $E)'
-        echo '            adb_push "$E" "$DSTPATH/$BE"'
-        echo '            NEWARGS="$NEWARGS $DSTPATH/$BE"'
-        echo '        else'
-        echo '            NEWARGS="$NEWARGS $E"'
+        echo '            echo $BE | grep -q -x libcrystax.so && continue'
+        echo '            echo $BE | grep -q -x libgnustl_shared.so && continue'
+        if [ -n "$ICU" ]; then
+            echo '            echo $BE | grep -q "^libicu.*" && continue'
+        fi
+        echo '            $STRIP --strip-unneeded $E >/dev/null 2>&1'
+        echo '            adb_push "$E" "$DSTPATH/$BE" && adb_shell "chmod 0755 $DSTPATH/$BE"'
+        echo '        done'
+        echo ''
+        echo '        NEWARGS=""'
+        echo '        for E in $ARGS; do'
+        echo '            if [ -e $E ]; then'
+        echo '                BE=$(basename $E)'
+        echo '                adb_push "$E" "$DSTPATH/$BE"'
+        echo '                NEWARGS="$NEWARGS $DSTPATH/$BE"'
+        echo '            else'
+        echo '                NEWARGS="$NEWARGS $E"'
+        echo '            fi'
+        echo '        done'
+        echo ''
+        echo '        adb_shell "cd $DSTPATH && LD_LIBRARY_PATH=$DEVPATH/lib:$DSTPATH TMPDIR=$DEVPATH/tmp ./$BF $NEWARGS"'
+        echo '        RC=$?'
+        echo '        $ADB shell "rm -r $DSTPATH" >/dev/null 2>&1'
+        echo '        if [ $RC -ne 0 ]; then'
+        echo '            log "RUN FAILED [\$?=$RC]: $F"'
+        echo '            exit $RC'
         echo '        fi'
+        echo ''
+        echo '        exit 0'
+        echo ''
+        echo '        )'
+        echo '        RC=$?'
+        echo '        test $RC -eq 0 || break'
         echo '    done'
-        echo ''
-        echo '    adb_shell "cd $DSTPATH && LD_LIBRARY_PATH=$DEVPATH/lib:$DSTPATH TMPDIR=$DEVPATH/tmp ./$BF $NEWARGS"'
-        echo '    RC=$?'
-        echo '    $ADB shell "rm -r $DSTPATH" >/dev/null 2>&1'
-        echo '    if [ $RC -ne 0 ]; then'
-        echo '        log "RUN FAILED [\$?=$RC]: $F"'
-        echo '        exit $RC'
+        echo '    if [ -f $ADBFAILED ]; then'
+        echo '        rm -f $ADBFAILED'
+        echo '        sleep 5'
+        echo '        continue'
         echo '    fi'
-        echo ''
-        echo '    exit 0'
-        echo ''
-        echo '    ) 3>"$LOCKDIR/$D.lock"'
-        echo '    RC=$?'
-        echo '    test $RC -eq 0 || exit $RC'
+        echo '    exit $RC'
         echo 'done'
         echo ''
         echo 'exit 0'
